# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer
name: Unity pipeline

on:
  push:
    branches:
      - "master"
  pull_request:
  release:
    types:
      - created

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: greetings
        run: echo 'hi'
  # play-tests:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: decentraland/renderer-build:2019.4
  #     env:
  #       BUILD_TARGET: WebGL
  #       BUILD_NAME: unity
  #   steps:
  #     - name: update git
  #       run: |
  #         add-apt-repository ppa:git-core/ppa
  #         apt-get update
  #         apt-get install -y git git-lfs
  #         git lfs install

  #     - name: checkout with LFS
  #       uses: actions/checkout@v2
  #       with:
  #         lfs: true

  #     # Run PlayMode tests
  #     - name: Run PlayMode tests
  #       env:
  #         UNITY_LICENSE_2019_4: ${{ secrets.UNITY_LICENSE_CONTENT_BASE64 }}
  #       run: bash ./ci-playmode-test.sh

  #     - name: print logs
  #       if: ${{ always() }}
  #       run: cat playmode-logs.txt

  #     - name: print test results
  #       if: ${{ always() }}
  #       run: |
  #         cat "playmode-results.xml"
  #         cat "playmode-results.xml" | grep Passed

  # build-artifacts:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: decentraland/renderer-build:2019.4
  #     env:
  #       BUILD_TARGET: WebGL
  #       BUILD_NAME: unity
  #   steps:
  #     - name: update git
  #       run: |
  #         add-apt-repository ppa:git-core/ppa
  #         apt-get update
  #         apt-get install -y git git-lfs
  #         git lfs install

  #     - name: checkout with LFS
  #       uses: actions/checkout@v2
  #       with:
  #         lfs: true

      # # Build
      # - name: Build
      #   if: ${{ always() }}
      #   env:
      #     UNITY_LICENSE_2019_4: ${{ secrets.UNITY_LICENSE_CONTENT_BASE64 }}
      #   run: ./ci-build.sh

      # - name: print logs
      #   if: ${{ always() }}
      #   run: cat build-logs.txt