# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer
name: Build pipeline

on:
  push:
  pull_request:

jobs:
  unity-pipeline:
    runs-on: ubuntu-latest
    container:
      image: decentraland/renderer-build:2019.4
      env:
        BUILD_TARGET: WebGL
        BUILD_PATH: ${{ github.workspace }}/Builds/unity
        BUILD_NAME: unity
    steps:
      - name: update git
        run: |
          add-apt-repository ppa:git-core/ppa
          apt-get update
          apt-get install -y git git-lfs
          git lfs install

      - name: checkout with LFS
        uses: actions/checkout@v2
        with:
          lfs: true

      # Run Editor tests
      - name: Run Editor tests
        if: ${{ always() }}
        env:
          UNITY_LICENSE_CONTENT_BASE64: ${{ secrets.UNITY_LICENSE_CONTENT_BASE64 }}
        run: sh ./ci-editmode-test.sh

      # # Run PlayMode tests
      # - name: Run PlayMode tests
      #   if: ${{ always() }}
      #   env:
      #     UNITY_LICENSE_CONTENT_BASE64: ${{ secrets.UNITY_LICENSE_CONTENT_BASE64 }}
      #   run: sh ./ci-playmode-test.sh

      # Build
      - name: Build
        if: ${{ always() }}
        env:
          UNITY_LICENSE_CONTENT_BASE64: ${{ secrets.UNITY_LICENSE_CONTENT_BASE64 }}
        run: sh ./ci-build.sh
